### PR TITLE
adit and add hobby 

### PR DESCRIPTION
**Pull request by xcf001**

### CODE REVIEW

**Comment by arzafr** [comment]
hey, how are you

**Comment by xcf001** [comment]
im fine

**Comment by arzafr** [comment]
where do you live

**Comment by xcf001** [comment]
japan

**Comment by arzafr** [comment]
can you be my partner ? you always help me

**Comment by xcf001** [comment]
of course we can, just call me nako

**Comment by arzafr** [comment]
ok nake, i will merge ur pull request

**Comment by arzafr** [comment]
*nako, sorry

**Comment by xcf001** [comment]
thanks

**Pull request merged**
